//! Agent dependencies collector.
//!
//! Computes a [`LayerSignature`] for an AI agent's dependency SBOM (Software
//! Bill of Materials). Follows the Ferrite collector pattern for struct-based
//! attestation, where the SBOM is provided as pre-computed data (e.g., from
//! Syft or Anchore).

use serde::{Deserialize, Serialize};

use crate::error::Result;
use crate::hash::Blake3Hash;
use crate::signature::{InputHash, LayerSignature, LayerType, SignatureMetadata};

use super::traits::LayerCollector;

/// SBOM format used to generate the dependency manifest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SbomFormat {
    /// SPDX 2.3 JSON.
    Spdx,
    /// CycloneDX 1.5 JSON.
    CycloneDx,
    /// Syft native JSON.
    Syft,
}

/// A single dependency entry in the SBOM.
#[derive(Clone, Debug, Serialize, Deserialize, schemars::JsonSchema)]
pub struct DependencyEntry {
    /// Package name.
    pub name: String,
    /// Package version.
    pub version: String,
    /// Package ecosystem (npm, cargo, pip, etc.).
    pub ecosystem: String,
    /// BLAKE3 hash of the package artifact.
    pub artifact_hash: Option<Blake3Hash>,
}

/// Configuration for agent dependencies collection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentDependenciesConfig {
    /// Raw SBOM content (pre-generated by Syft, Anchore, etc.).
    pub sbom_content: Vec<u8>,
    /// Format of the SBOM.
    pub sbom_format: SbomFormat,
    /// Agent name for metadata.
    pub agent_name: String,
    /// Optional lock file content (package-lock.json, Cargo.lock, etc.).
    pub lock_file_content: Option<Vec<u8>>,
}

/// Collector that produces a [`LayerSignature`] from an SBOM.
#[derive(Debug)]
pub struct AgentDependenciesCollector {
    config: AgentDependenciesConfig,
}

impl AgentDependenciesCollector {
    /// Create a new agent dependencies collector.
    #[must_use]
    pub fn new(config: AgentDependenciesConfig) -> Self {
        Self { config }
    }
}

impl LayerCollector for AgentDependenciesCollector {
    async fn collect(&self) -> Result<LayerSignature> {
        let sbom_hash = Blake3Hash::digest(&self.config.sbom_content);

        let format_canonical =
            serde_json::to_string(&self.config.sbom_format).unwrap_or_default();
        let format_hash = Blake3Hash::digest(format_canonical.as_bytes());

        let mut inputs = vec![
            InputHash {
                name: "sbom_hash".into(),
                hash: sbom_hash,
                size_bytes: Some(self.config.sbom_content.len() as u64),
            },
            InputHash {
                name: "sbom_format".into(),
                hash: format_hash,
                size_bytes: None,
            },
        ];

        if let Some(ref lock_content) = self.config.lock_file_content {
            inputs.push(InputHash {
                name: "lock_file_hash".into(),
                hash: Blake3Hash::digest(lock_content),
                size_bytes: Some(lock_content.len() as u64),
            });
        }

        // Compute composite hash from sorted inputs
        let mut sorted = inputs.clone();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));
        let mut hasher_data = Vec::with_capacity(sorted.len() * 32);
        for input in &sorted {
            hasher_data.extend_from_slice(&input.hash.0);
        }
        let composite = Blake3Hash::digest(&hasher_data);

        Ok(LayerSignature {
            layer: LayerType::AgentDependencies,
            hash: composite,
            metadata: SignatureMetadata {
                computed_at: chrono::Utc::now(),
                collector_version: env!("CARGO_PKG_VERSION").into(),
                source: self.config.agent_name.clone(),
                environment: None,
            },
            inputs,
        })
    }

    fn layer_type(&self) -> LayerType {
        LayerType::AgentDependencies
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config() -> AgentDependenciesConfig {
        AgentDependenciesConfig {
            sbom_content: br#"{"bomFormat":"CycloneDX","specVersion":"1.5","components":[]}"#
                .to_vec(),
            sbom_format: SbomFormat::CycloneDx,
            agent_name: "openclaw".into(),
            lock_file_content: Some(b"# Cargo.lock content".to_vec()),
        }
    }

    #[tokio::test]
    async fn collect_produces_signature() {
        let collector = AgentDependenciesCollector::new(make_config());
        let sig = collector.collect().await.unwrap();

        assert_eq!(sig.layer, LayerType::AgentDependencies);
        assert_eq!(sig.inputs.len(), 3);
        assert!(sig.inputs.iter().any(|i| i.name == "sbom_hash"));
        assert!(sig.inputs.iter().any(|i| i.name == "sbom_format"));
        assert!(sig.inputs.iter().any(|i| i.name == "lock_file_hash"));
    }

    #[tokio::test]
    async fn collect_hash_deterministic() {
        let c1 = AgentDependenciesCollector::new(make_config());
        let c2 = AgentDependenciesCollector::new(make_config());
        let s1 = c1.collect().await.unwrap();
        let s2 = c2.collect().await.unwrap();
        assert_eq!(s1.hash, s2.hash);
    }

    #[tokio::test]
    async fn collect_without_lock_file() {
        let config = AgentDependenciesConfig {
            sbom_content: b"sbom-data".to_vec(),
            sbom_format: SbomFormat::Syft,
            agent_name: "openclaw".into(),
            lock_file_content: None,
        };
        let collector = AgentDependenciesCollector::new(config);
        let sig = collector.collect().await.unwrap();
        assert_eq!(sig.inputs.len(), 2);
    }

    #[tokio::test]
    async fn collect_hash_changes_on_sbom_change() {
        let c1 = AgentDependenciesCollector::new(make_config());
        let s1 = c1.collect().await.unwrap();

        let mut config2 = make_config();
        config2.sbom_content = b"different-sbom".to_vec();
        let c2 = AgentDependenciesCollector::new(config2);
        let s2 = c2.collect().await.unwrap();

        assert_ne!(s1.hash, s2.hash);
    }

    #[test]
    fn layer_type_is_agent_dependencies() {
        let collector = AgentDependenciesCollector::new(make_config());
        assert_eq!(collector.layer_type(), LayerType::AgentDependencies);
    }

    #[test]
    fn sbom_format_serde_roundtrip() {
        for format in &[SbomFormat::Spdx, SbomFormat::CycloneDx, SbomFormat::Syft] {
            let json = serde_json::to_string(format).unwrap();
            let parsed: SbomFormat = serde_json::from_str(&json).unwrap();
            assert_eq!(&parsed, format);
        }
    }

    #[test]
    fn dependency_entry_serde_roundtrip() {
        let entry = DependencyEntry {
            name: "tokio".into(),
            version: "1.50.0".into(),
            ecosystem: "cargo".into(),
            artifact_hash: Some(Blake3Hash::digest(b"tokio-1.50.0")),
        };
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: DependencyEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.name, "tokio");
        assert_eq!(deserialized.version, "1.50.0");
    }
}
