//! Agent skills collector.
//!
//! Computes a [`LayerSignature`] for an AI agent's skill manifest by hashing
//! each skill individually and composing a Merkle root. Follows the Helm
//! collector pattern for directory-based traversal.

use std::path::Path;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::Result;
use crate::hash::Blake3Hash;
use crate::signature::{InputHash, LayerSignature, LayerType, SignatureMetadata};
use crate::traits::FileSystem;

use super::traits::LayerCollector;

/// Source of a skill — tracks provenance for attestation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SkillSource {
    /// Shipped with the agent distribution.
    Builtin,
    /// Installed from an attested skill store.
    Store(String),
    /// Dynamically generated by the agent (generation context hash).
    Generated(String),
    /// Manually installed from an external source (URL or path).
    External(String),
}

/// Compliance status for a skill attestation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SkillComplianceStatus {
    /// Passed all compliance checks.
    Attested,
    /// Awaiting compliance assessment.
    Pending,
    /// Failed one or more compliance controls.
    Failed(Vec<String>),
    /// Attestation has been revoked.
    Revoked,
}

/// Cryptographic attestation record for a single agent skill.
#[derive(Clone, Debug, Serialize, Deserialize, schemars::JsonSchema)]
pub struct SkillAttestation {
    /// Human-readable skill name.
    pub skill_name: String,
    /// BLAKE3 hash of the skill definition/source code.
    pub skill_hash: Blake3Hash,
    /// Where this skill came from.
    pub source: SkillSource,
    /// Permissions the skill requests (e.g., "shell", "network", "filesystem").
    pub permissions: Vec<String>,
    /// When this attestation was computed.
    pub attested_at: DateTime<Utc>,
    /// Current compliance status.
    pub compliance_status: SkillComplianceStatus,
}

/// A skill definition for hashing purposes.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SkillDefinition {
    /// Skill name.
    pub name: String,
    /// Skill source content (code or manifest).
    pub content: Vec<u8>,
    /// Permissions requested by the skill.
    pub permissions: Vec<String>,
    /// Source provenance.
    pub source: SkillSource,
}

/// Configuration for agent skills collection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSkillsConfig {
    /// Directory containing skill definitions.
    pub skills_dir: String,
    /// Optional manifest file listing all skills.
    pub manifest_path: Option<String>,
}

/// Collector that produces a [`LayerSignature`] from agent skill definitions.
#[derive(Debug)]
pub struct AgentSkillsCollector<F: FileSystem = crate::traits::MockFileSystem> {
    config: AgentSkillsConfig,
    fs: F,
}

impl<F: FileSystem> AgentSkillsCollector<F> {
    /// Create a new agent skills collector.
    #[must_use]
    pub fn new(config: AgentSkillsConfig, fs: F) -> Self {
        Self { config, fs }
    }
}

/// Compute an attestation for a single skill from its definition.
#[must_use]
pub fn attest_skill(def: &SkillDefinition) -> SkillAttestation {
    SkillAttestation {
        skill_name: def.name.clone(),
        skill_hash: Blake3Hash::digest(&def.content),
        source: def.source.clone(),
        permissions: def.permissions.clone(),
        attested_at: Utc::now(),
        compliance_status: SkillComplianceStatus::Pending,
    }
}

impl<F: FileSystem + Send + Sync> LayerCollector for AgentSkillsCollector<F> {
    async fn collect(&self) -> Result<LayerSignature> {
        let mut inputs = Vec::new();

        // If a manifest exists, hash it for the overall structure
        if let Some(ref manifest_path) = self.config.manifest_path {
            let mpath = Path::new(manifest_path);
            if let Ok(manifest_content) = self.fs.read_file(mpath).await {
                inputs.push(InputHash {
                    name: "manifest".into(),
                    hash: Blake3Hash::digest(&manifest_content),
                    size_bytes: Some(manifest_content.len() as u64),
                });
            }
        }

        // List and hash all skill files in the skills directory
        let skills_path = Path::new(&self.config.skills_dir);
        let entries = self.fs.read_dir(skills_path).await.map_err(|e| {
            crate::error::TameshiError::InvalidInput(format!(
                "failed to list skills directory '{}': {e}",
                self.config.skills_dir
            ))
        })?;

        let mut sorted_entries = entries;
        sorted_entries.sort();

        for entry in &sorted_entries {
            let name = entry
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default();
            if let Ok(content) = self.fs.read_file(entry).await {
                inputs.push(InputHash {
                    name: format!("skill:{name}"),
                    hash: Blake3Hash::digest(&content),
                    size_bytes: Some(content.len() as u64),
                });
            }
        }

        // Compute composite hash from sorted inputs
        let mut sorted = inputs.clone();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));
        let mut hasher_data = Vec::with_capacity(sorted.len() * 32);
        for input in &sorted {
            hasher_data.extend_from_slice(&input.hash.0);
        }
        let composite = if hasher_data.is_empty() {
            Blake3Hash::digest(b"empty-skills")
        } else {
            Blake3Hash::digest(&hasher_data)
        };

        Ok(LayerSignature {
            layer: LayerType::AgentSkills,
            hash: composite,
            metadata: SignatureMetadata {
                computed_at: Utc::now(),
                collector_version: env!("CARGO_PKG_VERSION").into(),
                source: self.config.skills_dir.clone(),
                environment: None,
            },
            inputs,
        })
    }

    fn layer_type(&self) -> LayerType {
        LayerType::AgentSkills
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::traits::MockFileSystem;
    use std::path::PathBuf;

    fn make_config() -> AgentSkillsConfig {
        AgentSkillsConfig {
            skills_dir: "/opt/openclaw/skills".into(),
            manifest_path: Some("/opt/openclaw/skills/manifest.json".into()),
        }
    }

    fn make_fs() -> MockFileSystem {
        let fs = MockFileSystem::new();
        fs.add_file(
            "/opt/openclaw/skills/manifest.json",
            b"{\"skills\": [\"search\", \"code_edit\"]}",
        );
        fs.add_dir(
            "/opt/openclaw/skills",
            vec![
                PathBuf::from("/opt/openclaw/skills/manifest.json"),
                PathBuf::from("/opt/openclaw/skills/search.py"),
                PathBuf::from("/opt/openclaw/skills/code_edit.py"),
            ],
        );
        fs.add_file("/opt/openclaw/skills/search.py", b"def search(): pass");
        fs.add_file(
            "/opt/openclaw/skills/code_edit.py",
            b"def code_edit(): pass",
        );
        fs
    }

    #[tokio::test]
    async fn collect_produces_signature() {
        let collector = AgentSkillsCollector::new(make_config(), make_fs());
        let sig = collector.collect().await.unwrap();

        assert_eq!(sig.layer, LayerType::AgentSkills);
        assert!(sig.inputs.len() >= 3);
        assert!(sig.inputs.iter().any(|i| i.name == "manifest"));
    }

    #[tokio::test]
    async fn collect_hash_deterministic() {
        let c1 = AgentSkillsCollector::new(make_config(), make_fs());
        let c2 = AgentSkillsCollector::new(make_config(), make_fs());
        let s1 = c1.collect().await.unwrap();
        let s2 = c2.collect().await.unwrap();
        assert_eq!(s1.hash, s2.hash);
    }

    #[tokio::test]
    async fn collect_empty_dir_produces_signature() {
        let fs = MockFileSystem::new();
        fs.add_dir("/opt/openclaw/skills", vec![]);
        let config = AgentSkillsConfig {
            skills_dir: "/opt/openclaw/skills".into(),
            manifest_path: None,
        };
        let collector = AgentSkillsCollector::new(config, fs);
        let sig = collector.collect().await.unwrap();
        assert_eq!(sig.layer, LayerType::AgentSkills);
        assert!(sig.inputs.is_empty());
    }

    #[test]
    fn layer_type_is_agent_skills() {
        let fs = MockFileSystem::new();
        let collector = AgentSkillsCollector::new(make_config(), fs);
        assert_eq!(collector.layer_type(), LayerType::AgentSkills);
    }

    #[test]
    fn skill_attestation_roundtrip() {
        let att = SkillAttestation {
            skill_name: "search".into(),
            skill_hash: Blake3Hash::digest(b"search-code"),
            source: SkillSource::Builtin,
            permissions: vec!["network".into()],
            attested_at: Utc::now(),
            compliance_status: SkillComplianceStatus::Attested,
        };
        let json = serde_json::to_string(&att).unwrap();
        let deserialized: SkillAttestation = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.skill_name, "search");
        assert_eq!(deserialized.skill_hash, att.skill_hash);
    }

    #[test]
    fn skill_source_variants_serde() {
        let sources = vec![
            SkillSource::Builtin,
            SkillSource::Store("store-123".into()),
            SkillSource::Generated("ctx-hash-abc".into()),
            SkillSource::External("https://example.com/skill.py".into()),
        ];
        for source in &sources {
            let json = serde_json::to_string(source).unwrap();
            let parsed: SkillSource = serde_json::from_str(&json).unwrap();
            assert_eq!(&parsed, source);
        }
    }

    #[test]
    fn skill_compliance_status_serde() {
        let statuses = vec![
            SkillComplianceStatus::Attested,
            SkillComplianceStatus::Pending,
            SkillComplianceStatus::Failed(vec!["NIST-AC-2".into()]),
            SkillComplianceStatus::Revoked,
        ];
        for status in &statuses {
            let json = serde_json::to_string(status).unwrap();
            let parsed: SkillComplianceStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(&parsed, status);
        }
    }

    #[test]
    fn attest_skill_produces_pending() {
        let def = SkillDefinition {
            name: "test".into(),
            content: b"def test(): pass".to_vec(),
            permissions: vec!["shell".into()],
            source: SkillSource::Builtin,
        };
        let att = attest_skill(&def);
        assert_eq!(att.skill_name, "test");
        assert_eq!(att.compliance_status, SkillComplianceStatus::Pending);
    }
}
